"""add_split_billing_accounts

Revision ID: b544cb859678
Revises: 3fea58f887d3
Create Date: 2026-02-16 18:20:10.741525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b544cb859678'
down_revision: Union[str, Sequence[str], None] = '3fea58f887d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adjustments', sa.Column('account_type', sa.String(), nullable=False))
    op.add_column('readings', sa.Column('debt_209', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('readings', sa.Column('overpayment_209', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('readings', sa.Column('debt_205', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('readings', sa.Column('overpayment_205', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('readings', sa.Column('total_209', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('readings', sa.Column('total_205', sa.Numeric(precision=12, scale=2), nullable=True))
    op.drop_column('readings', 'initial_overpayment')
    op.drop_column('readings', 'initial_debt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('initial_debt', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('readings', sa.Column('initial_overpayment', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_column('readings', 'total_205')
    op.drop_column('readings', 'total_209')
    op.drop_column('readings', 'overpayment_205')
    op.drop_column('readings', 'debt_205')
    op.drop_column('readings', 'overpayment_209')
    op.drop_column('readings', 'debt_209')
    op.drop_column('adjustments', 'account_type')
    # ### end Alembic commands ###
