"""Add soft delete and pg_trgm

Revision ID: b6fada547a41
Revises: 14ba0c616aeb
Create Date: 2026-02-21 13:19:23.568159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6fada547a41'
down_revision: Union[str, Sequence[str], None] = '14ba0c616aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ВАЖНО: Включаем расширение pg_trgm ДО создания индексов
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_index('idx_user_username_lower', table_name='users')
    op.create_index('idx_user_dormitory_trgm', 'users', ['dormitory'], unique=False, postgresql_using='gin', postgresql_ops={'dormitory': 'gin_trgm_ops'})
    op.create_index('idx_user_username_trgm', 'users', ['username'], unique=False, postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index('idx_user_username_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.drop_index('idx_user_dormitory_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'dormitory': 'gin_trgm_ops'})
    op.create_index('idx_user_username_lower', 'users', [sa.text('lower((username)::text)')], unique=False)
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###

    # Удаляем расширение при откате миграции
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")