"""init_db

Revision ID: 3fea58f887d3
Revises: 
Create Date: 2026-02-14 20:28:34.629819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fea58f887d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_periods_id'), 'periods', ['id'], unique=False)
    op.create_index(op.f('ix_periods_is_active'), 'periods', ['is_active'], unique=False)
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('maintenance_repair', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('social_rent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('heating', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('water_heating', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('water_supply', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sewage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('waste_disposal', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('electricity_per_sqm', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('electricity_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_is_active'), 'tariffs', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('dormitory', sa.String(), nullable=True),
    sa.Column('workplace', sa.String(), nullable=True),
    sa.Column('residents_count', sa.Integer(), nullable=True),
    sa.Column('total_room_residents', sa.Integer(), nullable=True),
    sa.Column('apartment_area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_username_lower', 'users', [sa.literal_column('lower(username)')], unique=False)
    op.create_index(op.f('ix_users_dormitory'), 'users', ['dormitory'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adj_user_period', 'adjustments', ['user_id', 'period_id'], unique=False)
    op.create_index(op.f('ix_adjustments_id'), 'adjustments', ['id'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.Column('hot_water', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('cold_water', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('electricity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('initial_debt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('initial_overpayment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('hot_correction', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('cold_correction', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('electricity_correction', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('sewage_correction', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_hot_water', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_cold_water', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_electricity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_sewage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_maintenance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_social_rent', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_waste', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_fixed_part', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('anomaly_flags', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reading_approved_period', 'readings', ['is_approved', 'period_id'], unique=False)
    op.create_index('idx_reading_user_approved', 'readings', ['user_id', 'is_approved'], unique=False)
    op.create_index('idx_reading_user_period', 'readings', ['user_id', 'period_id'], unique=False)
    op.create_index(op.f('ix_readings_id'), 'readings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_id'), table_name='readings')
    op.drop_index('idx_reading_user_period', table_name='readings')
    op.drop_index('idx_reading_user_approved', table_name='readings')
    op.drop_index('idx_reading_approved_period', table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_adjustments_id'), table_name='adjustments')
    op.drop_index('idx_adj_user_period', table_name='adjustments')
    op.drop_table('adjustments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_dormitory'), table_name='users')
    op.drop_index('idx_user_username_lower', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tariffs_is_active'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_periods_is_active'), table_name='periods')
    op.drop_index(op.f('ix_periods_id'), table_name='periods')
    op.drop_table('periods')
    # ### end Alembic commands ###
