"""init_arsenal

Revision ID: 0ea05e232b75
Revises: 
Create Date: 2026-02-18 13:48:38.812783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea05e232b75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('obj_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['accounting_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_objects_id'), 'accounting_objects', ['id'], unique=False)
    op.create_table('arsenal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arsenal_users_id'), 'arsenal_users', ['id'], unique=False)
    op.create_index(op.f('ix_arsenal_users_username'), 'arsenal_users', ['username'], unique=True)
    op.create_table('nomenclature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nomenclature_code'), 'nomenclature', ['code'], unique=False)
    op.create_index(op.f('ix_nomenclature_id'), 'nomenclature', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_number', sa.String(), nullable=True),
    sa.Column('doc_date', sa.DateTime(), nullable=True),
    sa.Column('operation_date', sa.DateTime(), nullable=True),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['arsenal_users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['accounting_objects.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['accounting_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_number'), 'documents', ['doc_number'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('document_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('nomenclature_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_items_id'), 'document_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_items_id'), table_name='document_items')
    op.drop_table('document_items')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_number'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_nomenclature_id'), table_name='nomenclature')
    op.drop_index(op.f('ix_nomenclature_code'), table_name='nomenclature')
    op.drop_table('nomenclature')
    op.drop_index(op.f('ix_arsenal_users_username'), table_name='arsenal_users')
    op.drop_index(op.f('ix_arsenal_users_id'), table_name='arsenal_users')
    op.drop_table('arsenal_users')
    op.drop_index(op.f('ix_accounting_objects_id'), table_name='accounting_objects')
    op.drop_table('accounting_objects')
    # ### end Alembic commands ###
