"""Add accounting fields to arsenal

Revision ID: 44e5b46ab02f
Revises: 74cc2ed1171b
Create Date: 2026-02-27 13:29:49.521559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e5b46ab02f'
down_revision: Union[str, Sequence[str], None] = '74cc2ed1171b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounting_objects', sa.Column('mol_name', sa.String(), nullable=True))
    op.add_column('document_items', sa.Column('inventory_number', sa.String(), nullable=True))
    op.add_column('document_items', sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('nomenclature', sa.Column('default_account', sa.String(), nullable=True))
    op.add_column('weapon_registry', sa.Column('inventory_number', sa.String(), nullable=True))
    op.add_column('weapon_registry', sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('weapon_registry', sa.Column('account_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_weapon_registry_inventory_number'), 'weapon_registry', ['inventory_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weapon_registry_inventory_number'), table_name='weapon_registry')
    op.drop_column('weapon_registry', 'account_code')
    op.drop_column('weapon_registry', 'price')
    op.drop_column('weapon_registry', 'inventory_number')
    op.drop_column('nomenclature', 'default_account')
    op.drop_column('document_items', 'price')
    op.drop_column('document_items', 'inventory_number')
    op.drop_column('accounting_objects', 'mol_name')
    # ### end Alembic commands ###
