"""Add weapon registry

Revision ID: 48bc51d3c31f
Revises: 0ea05e232b75
Create Date: 2026-02-18 16:36:40.821427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48bc51d3c31f'
down_revision: Union[str, Sequence[str], None] = '0ea05e232b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weapon_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('current_object_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_object_id'], ['accounting_objects.id'], ),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomenclature_id', 'serial_number', name='uix_nom_serial')
    )
    op.create_index(op.f('ix_weapon_registry_id'), 'weapon_registry', ['id'], unique=False)
    op.create_index(op.f('ix_weapon_registry_serial_number'), 'weapon_registry', ['serial_number'], unique=False)
    op.add_column('document_items', sa.Column('weapon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document_items', 'weapon_registry', ['weapon_id'], ['id'])
    op.drop_column('document_items', 'year_of_manufacture')
    op.drop_column('document_items', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_items', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('document_items', sa.Column('year_of_manufacture', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document_items', type_='foreignkey')
    op.drop_column('document_items', 'weapon_id')
    op.drop_index(op.f('ix_weapon_registry_serial_number'), table_name='weapon_registry')
    op.drop_index(op.f('ix_weapon_registry_id'), table_name='weapon_registry')
    op.drop_table('weapon_registry')
    # ### end Alembic commands ###
