"""arsenal-new

Revision ID: 5842080aa248
Revises: 44e5b46ab02f
Create Date: 2026-02-28 11:37:46.548716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5842080aa248'
down_revision: Union[str, Sequence[str], None] = '44e5b46ab02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weapon_registry', sa.Column('kbk', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapon_registry', 'kbk')
    # ### end Alembic commands ###
