"""Add weapon registry

Revision ID: 6fca595b2a30
Revises: 48bc51d3c31f
Create Date: 2026-02-18 17:40:10.803680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = '6fca595b2a30'
down_revision: Union[str, Sequence[str], None] = '48bc51d3c31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nomenclature', sa.Column('is_numbered', sa.Boolean(), nullable=False, server_default=text('true')))
    op.add_column('weapon_registry', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uix_nom_serial'), 'weapon_registry', type_='unique')
    op.create_unique_constraint('uix_nom_serial_obj', 'weapon_registry', ['nomenclature_id', 'serial_number', 'current_object_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_nom_serial_obj', 'weapon_registry', type_='unique')
    op.create_unique_constraint(op.f('uix_nom_serial'), 'weapon_registry', ['nomenclature_id', 'serial_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('weapon_registry', 'quantity')
    op.drop_column('nomenclature', 'is_numbered')
    # ### end Alembic commands ###
