"""Init GSM module tables

Revision ID: 74cc2ed1171b
Revises: eab29734a426
Create Date: 2026-02-27 11:29:16.952983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cc2ed1171b'
down_revision: Union[str, Sequence[str], None] = 'eab29734a426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsm_accounting_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('obj_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['gsm_accounting_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsm_accounting_objects_id'), 'gsm_accounting_objects', ['id'], unique=False)
    op.create_table('gsm_nomenclature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_packaged', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsm_nomenclature_code'), 'gsm_nomenclature', ['code'], unique=False)
    op.create_index(op.f('ix_gsm_nomenclature_id'), 'gsm_nomenclature', ['id'], unique=False)
    op.create_table('gsm_fuel_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomenclature_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('density', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_object_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_object_id'], ['gsm_accounting_objects.id'], ),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['gsm_nomenclature.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomenclature_id', 'batch_number', 'current_object_id', name='uix_gsm_nom_batch_obj')
    )
    op.create_index(op.f('ix_gsm_fuel_registry_batch_number'), 'gsm_fuel_registry', ['batch_number'], unique=False)
    op.create_index(op.f('ix_gsm_fuel_registry_id'), 'gsm_fuel_registry', ['id'], unique=False)
    op.create_table('gsm_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['gsm_accounting_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsm_users_id'), 'gsm_users', ['id'], unique=False)
    op.create_index(op.f('ix_gsm_users_username'), 'gsm_users', ['username'], unique=True)
    op.create_table('gsm_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_number', sa.String(), nullable=True),
    sa.Column('doc_date', sa.DateTime(), nullable=True),
    sa.Column('operation_date', sa.DateTime(), nullable=True),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['gsm_users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['gsm_accounting_objects.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['gsm_accounting_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsm_documents_doc_number'), 'gsm_documents', ['doc_number'], unique=False)
    op.create_index(op.f('ix_gsm_documents_id'), 'gsm_documents', ['id'], unique=False)
    op.create_table('gsm_document_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('fuel_id', sa.Integer(), nullable=True),
    sa.Column('nomenclature_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['gsm_documents.id'], ),
    sa.ForeignKeyConstraint(['fuel_id'], ['gsm_fuel_registry.id'], ),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['gsm_nomenclature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gsm_document_items_id'), 'gsm_document_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gsm_document_items_id'), table_name='gsm_document_items')
    op.drop_table('gsm_document_items')
    op.drop_index(op.f('ix_gsm_documents_id'), table_name='gsm_documents')
    op.drop_index(op.f('ix_gsm_documents_doc_number'), table_name='gsm_documents')
    op.drop_table('gsm_documents')
    op.drop_index(op.f('ix_gsm_users_username'), table_name='gsm_users')
    op.drop_index(op.f('ix_gsm_users_id'), table_name='gsm_users')
    op.drop_table('gsm_users')
    op.drop_index(op.f('ix_gsm_fuel_registry_id'), table_name='gsm_fuel_registry')
    op.drop_index(op.f('ix_gsm_fuel_registry_batch_number'), table_name='gsm_fuel_registry')
    op.drop_table('gsm_fuel_registry')
    op.drop_index(op.f('ix_gsm_nomenclature_id'), table_name='gsm_nomenclature')
    op.drop_index(op.f('ix_gsm_nomenclature_code'), table_name='gsm_nomenclature')
    op.drop_table('gsm_nomenclature')
    op.drop_index(op.f('ix_gsm_accounting_objects_id'), table_name='gsm_accounting_objects')
    op.drop_table('gsm_accounting_objects')
    # ### end Alembic commands ###
