"""arsenal-doc

Revision ID: 7e8bc3dc33d2
Revises: 5842080aa248
Create Date: 2026-02-28 16:31:08.623470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8bc3dc33d2'
down_revision: Union[str, Sequence[str], None] = '5842080aa248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('attached_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'attached_file_path')
    # ### end Alembic commands ###
