"""add role and object_id

Revision ID: eab29734a426
Revises: 6fca595b2a30
Create Date: 2026-02-24 13:18:29.952768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab29734a426'
down_revision: Union[str, Sequence[str], None] = '6fca595b2a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arsenal_users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('arsenal_users', sa.Column('object_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'arsenal_users', 'accounting_objects', ['object_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arsenal_users', type_='foreignkey')
    op.drop_column('arsenal_users', 'object_id')
    op.drop_column('arsenal_users', 'role')
    # ### end Alembic commands ###
